---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: meliuz/Programa-de-Estagio
  description: |-
    # Instruções para configurar e acessar os dados

    Antes de começar a prova, escolha em qual formato será entregue, podendo ser
    feito em Python ou G. Sh...
  name: Programa-de-Estagio
spec:
  lifecycle: production
  type: service
  owner: estrategia-data-analytics
